# Generated by Django 4.0.3 on 2022-03-24 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphEntity',
            fields=[
                ('wikidataId', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Wikidata Id')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
            ],
        ),
        migrations.CreateModel(
            name='GraphFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftEntity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_entity', to='api.graphentity')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='api.graphentity')),
                ('rightEntity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_entity', to='api.graphentity')),
            ],
        ),
        migrations.AddConstraint(
            model_name='graphfact',
            constraint=models.UniqueConstraint(fields=('leftEntity', 'property', 'rightEntity'), name='factConstraint'),
        ),
    ]
