# Generated by Django 4.0.3 on 2022-03-24 15:20
# This is migration is solely for the purpose of demonstrating the application.
# TODO: Remove this if moving to a production environment.

from django.db import migrations
from api.models import GraphEntity, GraphFact
from django.contrib.auth.models import User
from datetime import date

def populate_graph_entities_facts(apps, schema_editor):
    leftEntity = GraphEntity("Q42", "Douglas Adams")
    leftEntity.save()

    property = GraphEntity("P106", "occupation")
    property.save()

    rightEntity = GraphEntity("Q214917", "playwright")
    rightEntity.save()

    GraphFact(leftEntity=leftEntity, property=property, rightEntity=rightEntity).save()

def create_admin_user(apps, schema_editor):
    admin = User.objects.create(
        username ='admin',
        email = 'admin@graphexplorer.com',
        first_name = 'Mr.',
        last_name = 'Admin',
        is_staff = True,
        last_login = date.now()
    )

    admin.set_password('password')
    admin.save()

    user = User.objects.create(
        username ='user',
        email = 'user@graphexplorer.com',
        first_name = 'Jane',
        last_name = 'Doe',
        last_login = date.now()
    )

    user.set_password('password')
    user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin_user),
        migrations.RunPython(populate_graph_entities_facts),
    ]
